# Generated by Django 3.1.2 on 2020-10-20 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_city_mst',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='portal.tbl_state_mst', verbose_name='State ID'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='belongs_to_company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to', to='portal.tbl_company_mst'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='currency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.tbl_currency_mst'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='location_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_location_mst', verbose_name='Location Ref ID'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='management_belongs_to_company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_by', to='portal.tbl_company_mst'),
        ),
        migrations.AlterField(
            model_name='tbl_location_mst',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='portal.tbl_city_mst', verbose_name='City ID'),
        ),
        migrations.AlterField(
            model_name='tbl_location_mst',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_country_mst', verbose_name='Country ID'),
        ),
        migrations.AlterField(
            model_name='tbl_location_mst',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_state_mst', verbose_name='State ID'),
        ),
        migrations.AlterField(
            model_name='tbl_state_mst',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='portal.tbl_country_mst', verbose_name='Country ID'),
        ),
        migrations.AddConstraint(
            model_name='tbl_location_mst',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted='N'), fields=('location_name',), name='unique if not deleted'),
        ),
    ]
