# Generated by Django 3.1.2 on 2020-10-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20201020_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_city_mst',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_state_mst', verbose_name='State ID'),
        ),
        migrations.AddField(
            model_name='tbl_state_mst',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_country_mst', verbose_name='Country ID'),
        ),
    ]
