# Generated by Django 3.1.2 on 2020-10-20 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20201020_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_city_mst',
            name='state_id',
            field=models.IntegerField(default=0,verbose_name='State ID'),
        ),
        migrations.AddField(
            model_name='tbl_state_mst',
            name='country_id',
            field=models.IntegerField(default=0, verbose_name='Country ID'),
        ),
    ]