# Generated by Django 3.1.2 on 2020-10-20 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20201020_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_state_mst',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='portal.tbl_country_mst', verbose_name='Country ID'),
        ),
    ]
