# Generated by Django 3.1.2 on 2020-10-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20201020_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_1_field_id',
            field=models.CharField(default=0, max_length=20, verbose_name='Source Name 1 Field Name ID'),
        ),
        migrations.AddField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_2_field_id',
            field=models.CharField(default=0, max_length=20, verbose_name='Source Name 2 Field Name ID'),
        ),
        migrations.AddField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_3_field_id',
            field=models.CharField(default=0, max_length=20, verbose_name='Source Name 3 Field Name ID'),
        ),
        migrations.AddField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_4_field_id',
            field=models.CharField(default=0, max_length=20, verbose_name='Source Name 4 Field Name ID'),
        ),
    ]
