# Generated by Django 3.1.2 on 2020-10-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20201020_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='contact_person_mobile_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
