# Generated by Django 3.1.2 on 2020-10-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20201021_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_master',
            name='master_type',
            field=models.CharField(max_length=50, verbose_name='Master Type'),
        ),
    ]
