# Generated by Django 3.1.2 on 2020-10-22 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20201022_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_api_definition_mst',
            name='source_name_ref_id',
        ),
        migrations.RemoveField(
            model_name='tbl_api_definition_mst',
            name='time_out',
        ),
        migrations.AlterField(
            model_name='tbl_api_definition_details',
            name='api_field_data_type_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='api_field_data_type', to='portal.tbl_master', verbose_name='API Data Type Ref ID'),
        ),
        migrations.AlterField(
            model_name='tbl_api_definition_details',
            name='field_data_type_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_master', verbose_name='Field Data Type Ref ID'),
        ),
        migrations.AlterField(
            model_name='tbl_api_definition_mst',
            name='name',
            field=models.CharField(max_length=20, verbose_name='API Name'),
        ),
        migrations.AlterField(
            model_name='tbl_api_definition_mst',
            name='request_type_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_master', verbose_name='Request Type Ref ID'),
        ),
    ]
