# Generated by Django 3.1.2 on 2020-10-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20201022_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_api_definition_mst',
            name='self_channel_ref_id',
        ),
    ]
