# Generated by Django 3.1.2 on 2020-10-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_tbl_reason_mst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_api_definition_details',
            name='field_name',
            field=models.CharField(max_length=20, verbose_name='Field Name'),
        ),
    ]
