# Generated by Django 3.1.2 on 2020-10-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20201023_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_reason_mst',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
