# Generated by Django 3.1.2 on 2020-10-27 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20201023_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_channel_mst',
            name='company_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='portal.tbl_company_mst', verbose_name='Company Ref Id'),
        ),
    ]
