# Generated by Django 3.1.2 on 2020-10-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20201027_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_source_mst',
            name='channel_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_channel_mst', verbose_name='Channel Ref Id'),
        ),
        migrations.AddField(
            model_name='tbl_source_mst',
            name='network_type_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='Network_Type', to='portal.tbl_master', verbose_name='Network Type Ref Id'),
        ),
        migrations.AlterField(
            model_name='tbl_source_mst',
            name='company_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='portal.tbl_company_mst', verbose_name='Company Ref Id'),
        ),
    ]
