# Generated by Django 3.1.2 on 2020-10-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20201027_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_employee_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='First name')),
                ('middle_name', models.CharField(max_length=15, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=15, verbose_name='Last name')),
                ('employee_seq_no', models.CharField(max_length=20, verbose_name='Employee Seq No')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('pincode', models.CharField(max_length=6, verbose_name='Pincode')),
                ('address1', models.CharField(max_length=200, verbose_name='Address 1')),
                ('address2', models.CharField(max_length=200, verbose_name='Address 2')),
                ('address3', models.CharField(max_length=200, verbose_name='Address 3')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('city_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_city_mst', verbose_name='City ID')),
                ('company_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_company_mst', verbose_name='Company Ref Id')),
                ('country_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_country_mst', verbose_name='Country ID')),
                ('role_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_role_mst', verbose_name='Role Ref Id')),
                ('state_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_state_mst', verbose_name='State ID')),
            ],
        )
    ]
