# Generated by Django 3.1.2 on 2020-10-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20201027_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_api_definition_details',
            name='header_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='initialItemRow', to='portal.tbl_api_definition_mst', verbose_name='Header Ref ID'),
        ),
        migrations.AlterField(
            model_name='tbl_api_definition_standard_details',
            name='header_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='initialItemRow', to='portal.tbl_api_definition_standard_mst', verbose_name='Header Ref ID'),
        ),
    ]
