# Generated by Django 3.1.2 on 2020-10-28 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_auto_20201027_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_reconcilation_process_mst',
            name='api_ref_id',
        ),
        migrations.RemoveField(
            model_name='tbl_reconcilation_process_mst',
            name='request_type_ref_id',
        ),
        migrations.AddField(
            model_name='tbl_reconcilation_process_details',
            name='api_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_api_definition_mst', verbose_name='API Ref ID'),
        ),
        migrations.AddField(
            model_name='tbl_reconcilation_process_details',
            name='request_type_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='api_request_type', to='portal.tbl_master', verbose_name='Request Type Ref ID'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_process_details',
            name='operation_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_master', verbose_name='Operation Ref ID'),
        ),
        migrations.AddConstraint(
            model_name='tbl_api_definition_mst',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted='N'), fields=('name', 'company_ref_id', 'channel_ref_id'), name='tbl_api_definition_mst unique if not deleted'),
        ),
    ]
