# Generated by Django 3.1.2 on 2020-10-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_auto_20201028_1823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_employee_mst',
        ),
    ]
