# Generated by Django 3.1.2 on 2020-10-29 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_tbl_employee_mst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_reconcilation_process_details',
            name='source_name_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_source_mst', verbose_name='Source Name Ref ID'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_process_mst',
            name='reconcilation_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_reconcilation_definition_mst', verbose_name='Reconcilation Ref ID'),
        ),
    ]
