# Generated by Django 3.1.2 on 2020-10-29 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_auto_20201029_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_source_mst',
            old_name='name',
            new_name='source_name',
        ),
        migrations.AlterField(
            model_name='tbl_source_details',
            name='field_data_type_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='Field_Type', to='portal.tbl_master', verbose_name='Field Data Type ID'),
        ),
        migrations.AlterField(
            model_name='tbl_source_details',
            name='section_identifier_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Section_Type', to='portal.tbl_master', verbose_name='Section Reference ID'),
        ),
    ]
