# Generated by Django 3.1.2 on 2020-10-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_auto_20201029_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_source_details',
            name='is_key_field',
            field=models.BooleanField(default=False, verbose_name='Is Key Field'),
        ),
        migrations.AlterField(
            model_name='tbl_source_details',
            name='is_primary_field',
            field=models.BooleanField(default=False, verbose_name='Is Primary Field'),
        ),
    ]
