# Generated by Django 3.1.2 on 2020-10-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_auto_20201029_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_schedule_process_mst',
            name='frequncy_ref_id',
        ),
        migrations.AddField(
            model_name='tbl_schedule_process_mst',
            name='frequency_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_master', verbose_name='Frequency Ref ID'),
        ),
        migrations.AlterField(
            model_name='tbl_schedule_process_mst',
            name='process_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_reconcilation_process_mst', verbose_name='Process Ref ID'),
        ),
    ]
