# Generated by Django 3.1.2 on 2020-11-03 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_tbl_workflow_mst'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_sourcetable_fields_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_identifier_id', models.IntegerField(default=0, verbose_name='Section Identifier ID')),
                ('field_name', models.CharField(max_length=20, verbose_name='Field Name')),
                ('field_length', models.IntegerField(verbose_name='Field Length')),
                ('is_key_field', models.BooleanField(default=False, verbose_name='Is Key Field')),
                ('is_primary_field', models.BooleanField(default=False, verbose_name='Is Primary Field')),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
                ('field_data_type_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_master', verbose_name='Field Data Type ID')),
            ],
        ),
    ]
