# Generated by Django 3.1.2 on 2020-11-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_auto_20201103_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_sourcetable_fields_mst',
            old_name='section_identifier_id',
            new_name='section_identifier',
        ),
    ]
