# Generated by Django 3.1.2 on 2020-11-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_auto_20201103_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_sourcetable_fields_mst',
            name='field_name',
            field=models.CharField(max_length=40, verbose_name='Field Name'),
        ),
    ]
