# Generated by Django 3.1.2 on 2020-11-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_auto_20201105_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_1_section_identifier_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Source Name 1 Section Identifier ID'),
        ),
    ]
