# Generated by Django 3.1.2 on 2020-11-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_auto_20201105_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_1_field_id',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='Source Name 1 Field Name ID'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_1_field_name',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='Source Name 1 Field Name'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_1_ref_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='details_source_name1', to='portal.tbl_source_mst', verbose_name='Source Name 1 Ref ID'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_2_field_id',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='Source Name 2 Field Name ID'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_2_field_name',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='Source Name 2 Field Name'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_2_ref_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='details_source_name2', to='portal.tbl_source_mst', verbose_name='Source Name 2 Ref ID'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_2_section_identifier_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Source Name 2 Section Identifier ID'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_3_field_id',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='Source Name 3 Field Name ID'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_3_field_name',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='Source Name 3 Field Name'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_3_ref_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='details_source_name3', to='portal.tbl_source_mst', verbose_name='Source Name 3 Ref ID'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_3_section_identifier_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Source Name 3 Section Identifier ID'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_4_field_id',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='Source Name 4 Field Name ID'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_4_field_name',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='Source Name 4 Field Name'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_4_ref_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='details_source_name4', to='portal.tbl_source_mst', verbose_name='Source Name 4 Ref ID'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_details',
            name='source_name_4_section_identifier_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Source Name 4 Section Identifier ID'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_mst',
            name='source_name3_ref_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_name3', to='portal.tbl_source_mst', verbose_name='Source Name 3 Ref ID'),
        ),
        migrations.AlterField(
            model_name='tbl_reconcilation_definition_mst',
            name='source_name4_ref_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_name4', to='portal.tbl_source_mst', verbose_name='Source Name 4 Ref ID'),
        ),
    ]
