# Generated by Django 3.1.2 on 2020-10-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20201020_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_city_mst',
            name='state_id',
            field=models.IntegerField(verbose_name='State ID'),
        ),
        migrations.AlterField(
            model_name='tbl_state_mst',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='portal.tbl_country_mst', verbose_name='Country ID'),
        ),
    ]
