# Generated by Django 3.1.2 on 2020-10-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20201020_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_state_mst',
            name='country_id',
        ),
    ]
