# Generated by Django 3.1.2 on 2020-10-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_tbl_state_mst_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_state_mst',
            name='country_id',
            field=models.IntegerField(default=0, verbose_name='Country ID'),
        ),
        migrations.AlterField(
            model_name='tbl_city_mst',
            name='state_id',
            field=models.IntegerField(default=0, verbose_name='State ID'),
        ),
    ]
