# Generated by Django 3.1.2 on 2020-10-20 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_remove_tbl_city_mst_state_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_city_mst',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='portal.tbl_state_mst', verbose_name='State ID'),
        ),
    ]
