# Generated by Django 3.1.2 on 2020-10-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20201020_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_location_mst',
            old_name='address_1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='tbl_location_mst',
            old_name='address_2',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='tbl_location_mst',
            old_name='address_3',
            new_name='address3',
        ),
    ]
