# Generated by Django 3.1.2 on 2020-10-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20201020_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_location_mst',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='tbl_location_mst',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='tbl_location_mst',
            name='address3',
        ),
        migrations.AddConstraint(
            model_name='tbl_location_mst',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted='N'), fields=('location_name',), name='unique if not deleted'),
        ),
    ]
