class tbl_api_definition_standard_mst(models.Model):
    transaction_id = models.IntegerField(default=0,verbose_name='Transaction ID')
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    company_ref_id =models.ForeignKey('Tbl_Company_Mst',on_delete=models.CASCADE,related_name='companies')
    channel_ref_id = models.CharField(max_length=20,verbose_name='Channel Ref Id')
    from_date = models.DateField(verbose_name="From Date",auto_now_add=False)
    to_date = models.DateField(verbose_name="To Date",auto_now_add=False)
    revision_status = models.CharField(max_length=20,verbose_name="Revision Status")
    self_api= models.CharField(max_length=20,verbose_name='Self API')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")      

class tbl_api_definition_standard_details(models.Model):
    transaction_ref_id = models.IntegerField(default=0,verbose_name='Transaction Ref ID')
    request_type_ref_id =models.IntegerField(max_length=20,verbose_name='Channel Ref Id')
    api_type_ref_id = models.IntegerField(max_length=20,verbose_name='Channel Ref Id')
    protocol_type_ref_id = models.IntegerField(max_length=20,verbose_name='From Date')
    file_format_type_ref_id = models.IntegerField(max_length=20,verbose_name='To Date')
    authentication_type_ref_id = models.IntegerField(max_length=20,verbose_name='Status')
    communication_ref_id= models.IntegerField(max_length=20,verbose_name='Self A')
    session_key_encryption_type_ref_id= models.IntegerField(max_length=20,verbose_name='Self A')
    encryption_type_ref_id= models.IntegerField(max_length=20,verbose_name='Self A')
    port= models.IntegerField(max_length=20,verbose_name='Self A')
    verification_algorithm_ref_id= models.CharField(max_length=20,verbose_name='Self A')
    end_point_url= models.CharField(max_length=20,verbose_name='Self A')
    time_out= models.IntegerField(max_length=20,verbose_name='Self A')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")  
 
class tbl_api_definition_mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    name = models.IntegerField(default=0,verbose_name='Transaction ID')
    request_type_ref_id =models.IntegerField(default=0,verbose_name='Channel Ref Id')
    company_ref_id = models.ForeignKey("tbl_company_mst", default=0, verbose_name="Company Ref Id", on_delete=models.PROTECT)
   channel_ref_id = models.ForeignKey("tbl_channel_mst", default=0,verbose_name="Channel Ref Id",on_delete=models.PROTECT)
    self_channel_ref_id = models.ForeignKey("tbl_channel_mst", default=0,verbose_name="Self Channel Ref Id",on_delete=models.PROTECT)
    source_name_ref_id = models.IntegerField(default=0,verbose_name='Source Name Ref ID')
    from_date = models.DateField(verbose_name="From Date",auto_now_add=False)
    to_date = models.DateField(verbose_name="To Date",auto_now_add=False)
    revision_status = models.CharField(max_length=20,verbose_name="Revision Status")
    time_out= models.IntegerField(max_length=20,verbose_name='Time out')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")   

class tbl_api_definition_details(models.Model):
    header_ref_id = models.ForeignKey("tbl_api_definition_mst", default=0,verbose_name="Header Ref ID",on_delete=models.PROTECT)
    api_field_name =models.IntegerField(max_length=20,verbose_name='API Field Name')
    api_field_data_type_ref_id = models.IntegerField(max_length=20,verbose_name='API Field Data Type Ref Id')
    api_field_length = models.IntegerField(max_length=20,verbose_name='API Field Length')
    table_name = models.IntegerField(max_length=20,verbose_name='To Date')
    field_name =models.IntegerField(max_length=20,verbose_name='Field Name')
    field_data_type_ref_id = models.IntegerField(max_length=20,verbose_name='Field Data Type Ref Id')
    field_length = models.IntegerField(max_length=20,verbose_name='Field Length')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")  

class tbl_reconcilation_process_mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    name = models.CharField(max_length=20,verbose_name='Process Name')
    reconcilation_ref_id = models.IntegerField(default=0,verbose_name='Reconcilation Ref ID')
    api_ref_id = models.IntegerField(default=0,verbose_name='API Ref ID')
    request_type_ref_id =models.IntegerField(default=0,verbose_name='Request Type Ref Id')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")  

class tbl_reconcilation_process_details(models.Model):
    header_ref_id = models.IntegerField(default=0,verbose_name='Header Ref ID')
    operation_ref_id = models.IntegerField(default=0,verbose_name='Operation Ref ID')
    source_name_ref_id = models.IntegerField(default=0,verbose_name='Source Name Ref ID')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")        

class tbl_schedule_process_mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    process_ref_id = models.IntegerField(default=0,verbose_name='Process Ref ID')
    frequncy_ref_id = models.IntegerField(default=0,verbose_name='Frequency Ref ID')
    start_time = models.DateTimeField(default=timezone.localtime,verbose_name="Start Time")
    planned_execution_ref_id =models.IntegerField(default=0,verbose_name='Planned Execution Ref Id')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")      

class tbl_activity_mst(models.Model):
    process_ref_id = models.IntegerField(default=0,verbose_name='Process Ref ID')
    transaction_sequence_no = models.IntegerField(default=0,verbose_name='Transaction Sequence No')
    planned_start_time = models.DateTimeField(default=0,verbose_name='Process Ref ID')
    actual_start_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    actual_end_time = models.DateTimeField(default=timezone.localtime,verbose_name="Actual Date Time")
    status = models.CharField(verbose_name='Status')
    log_ref_id = models.IntegerField(default=0,verbose_name='Log Ref ID')
    remarks = models.TextField(verbose_name='Remarks')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

class tbl_activity_details(models.Model):
    header_ref_id = models.ForeignKey("tbl_activity_mst", default=0,verbose_name="Header Ref ID",on_delete=models.PROTECT)
    operation_ref_id = models.IntegerField(default=0,verbose_name='Operation Ref ID')
    transaction_sub_sequence_no = models.IntegerField(default=0,verbose_name='Transaction Sub Sequence No')
    actual_start_time = models.DateTimeField(default=timezone.localtime,verbose_name="Actual Start Time")
    actual_end_time = models.DateTimeField(default=timezone.localtime,verbose_name="Actual End Time")
    status = models.CharField(verbose_name='Status')
    log_ref_id = models.IntegerField(default=0,verbose_name='Log Ref ID')
    remarks = models.TextField(verbose_name='Remarks')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")
        