class tbl_reconcilation_definition_mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    company_ref_id = models.ForeignKey("tbl_company_mst", default=0, verbose_name="Company Ref Id", on_delete=models.PROTECT)
    name = models.CharField(max_length=20,verbose_name='Reconcilation Name')
    recon_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Recon Type Ref ID",on_delete=models.PROTECT)
    # source_name1_ref_id = models.ForeignKey("tbl_source_mst", default=0,verbose_name="Source Name 1 Ref ID",on_delete=models.PROTECT)
    # source_name2_ref_id = models.ForeignKey("tbl_source_mst", default=0,verbose_name="Source Name 2 Ref ID",on_delete=models.PROTECT)
    # source_name3_ref_id = models.ForeignKey("tbl_source_mst", default=0,verbose_name="Source Name 3 Ref ID",on_delete=models.PROTECT)
    # source_name4_ref_id = models.ForeignKey("tbl_source_mst", default=0,verbose_name="Source Name 4 Ref ID",on_delete=models.PROTECT)
    # source_name5_ref_id = models.ForeignKey("tbl_source_mst", default=0,verbose_name="Source Name 5 Ref ID",on_delete=models.PROTECT)
    source_name1_ref_id = models.CharField(max_length=20,verbose_name='Source Name 1 Ref ID')
    source_name2_ref_id = models.CharField(max_length=20,verbose_name='Source Name 2 Ref ID')
    source_name3_ref_id = models.CharField(max_length=20,verbose_name='Source Name 3 Ref ID')
    source_name4_ref_id = models.CharField(max_length=20,verbose_name='Source Name 4 Ref ID')
    source_name5_ref_id = models.CharField(max_length=20,verbose_name='Source Name 5 Ref ID')
    recon_rule = models.TextField(verbose_name='Recon Rule')
    probable_match_rule = models.TextField(verbose_name='Probable Match Rule')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")  
 
class tbl_reconcilation_definition_details(models.Model):
    header_ref_id = models.ForeignKey("tbl_reconcilation_definition_mst", default=0,verbose_name="Header Ref ID",on_delete=models.PROTECT)
    source_name_ref_id = models.ForeignKey("tbl_source_mst", default=0,verbose_name="Source Name Ref ID",on_delete=models.PROTECT)
    source_sequence = models.IntegerField(default=0,verbose_name='Source Sequence')
    source_header_field_name = models.CharField(max_length=20,verbose_name='Source Header Field Name')
    source_details_field_name = models.CharField(max_length=20,verbose_name='Source Details Field Name')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

class tbl_api_definition_standard_mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    company_ref_id = models.ForeignKey("tbl_company_mst", default=0, verbose_name="Company Ref Id", on_delete=models.PROTECT)
    channel_ref_id = models.ForeignKey("tbl_channel_mst", default=0,verbose_name="Channel Ref Id",on_delete=models.PROTECT)
    from_date = models.DateField(verbose_name="From Date",auto_now_add=False)
    to_date = models.DateField(verbose_name="To Date",auto_now_add=False)
    revision_status = models.CharField(max_length=20,verbose_name="Revision Status")
    self_api= models.CharField(default='N',max_length=1,verbose_name='Self API')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")      

class tbl_api_definition_standard_details(models.Model):
    header_ref_id = models.ForeignKey("tbl_api_definition_standard_mst", default=0,verbose_name="Header Ref ID",on_delete=models.PROTECT)
    request_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Request Type Ref Id",on_delete=models.PROTECT)
    api_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="API Type Ref Id",on_delete=models.PROTECT)
    protocol_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Protocol Type Ref ID",on_delete=models.PROTECT)
    file_format_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="File Format Type Ref ID",on_delete=models.PROTECT)
    authentication_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Authentication Type Ref Id",on_delete=models.PROTECT)
    communication_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Communication Ref Id",on_delete=models.PROTECT)
    session_key_encryption_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Session Key Ref Id",on_delete=models.PROTECT)
    encryption_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Encryption Type Ref Id",on_delete=models.PROTECT)
    port= models.IntegerField(default=0,verbose_name='Port')
    verification_algorithm_ref_id= models.ForeignKey("tbl_master", default=0,verbose_name="Verification Algo Type Ref Id",on_delete=models.PROTECT)
    end_point_url= models.CharField(max_length=20,verbose_name='End Point URL')
    time_out= models.IntegerField(default=0,verbose_name='Time Out')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")  

class tbl_api_definition_standard_mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    company_ref_id = models.ForeignKey("tbl_company_mst", default=0, verbose_name="Company Ref Id", on_delete=models.PROTECT)
    channel_ref_id = models.ForeignKey("tbl_channel_mst", default=0,verbose_name="Channel Ref Id",on_delete=models.PROTECT)
    from_date = models.DateField(verbose_name="From Date",auto_now_add=False)
    to_date = models.DateField(verbose_name="To Date",auto_now_add=False)
    revision_status = models.CharField(max_length=20,verbose_name="Revision Status")
    self_api= models.CharField(default='N',max_length=1,verbose_name='Self API')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")      

class tbl_api_definition_standard_details(models.Model):
    header_ref_id = models.ForeignKey("tbl_api_definition_standard_mst", default=0,verbose_name="Header Ref ID",on_delete=models.PROTECT)
    request_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Request Type Ref Id",on_delete=models.PROTECT)
    api_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="API Type Ref Id",on_delete=models.PROTECT)
    protocol_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Protocol Type Ref ID",on_delete=models.PROTECT)
    file_format_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="File Format Type Ref ID",on_delete=models.PROTECT)
    authentication_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Authentication Type Ref Id",on_delete=models.PROTECT)
    communication_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Communication Ref Id",on_delete=models.PROTECT)
    session_key_encryption_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Session Key Ref Id",on_delete=models.PROTECT)
    encryption_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Encryption Type Ref Id",on_delete=models.PROTECT)
    port= models.IntegerField(default=0,verbose_name='Port')
    verification_algorithm_ref_id= models.ForeignKey("tbl_master", default=0,verbose_name="Verification Algo Type Ref Id",on_delete=models.PROTECT)
    end_point_url= models.CharField(max_length=20,verbose_name='End Point URL')
    time_out= models.IntegerField(default=0,verbose_name='Time Out')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")                   