from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
ROLES = ((1,"Administrator"),(2,"Assistant Manager Materials"),(3,"Executive Sales Operator"),(4,"Purchase Manager"))

class tbl_login_mst(models.Model):
    '''
    Columns taken from default User model: is_active, username & password
    '''
    user = models.OneToOneField(User,max_length=140, default=0,on_delete = models.CASCADE)
    company_id = models.IntegerField(default=0,verbose_name="Company ID")
    role_ref_id = models.ForeignKey('Tbl_Role_Mst', default=0,verbose_name="Role ID",on_delete=models.CASCADE)
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")    

class Tbl_Role_Mst(models.Model):
    role_name = models.CharField(max_length=30,verbose_name='Role Name')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")    

class Tbl_Country_Mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    name = models.CharField(max_length=20,verbose_name='Name')
    short_name = models.CharField(max_length=20,verbose_name='Short Name')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")    

class Tbl_Uom_Mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    uom_code = models.CharField(max_length=20,verbose_name='UOM Code')
    uom_description = models.TextField(verbose_name='UOM Description')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")
    
class Tbl_Currency_Mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    currency_code = models.CharField(max_length=10,verbose_name='Currency Code')
    currency_name = models.CharField(max_length=30, verbose_name='Currency Name')
    symbol = models.CharField(max_length=20,verbose_name='Symbol')
    country_id = models.IntegerField(default=0,verbose_name='Country ID')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

class Tbl_State_Mst(models.Model):
    share_id =  models.IntegerField(default=0,verbose_name='Share ID')
    country_id = models.IntegerField(default=0,verbose_name='Country ID')
    state = models.CharField(max_length=20, verbose_name='State')
    gst_state_code = models.IntegerField(default=0)
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

class Tbl_City_Mst(models.Model):
    share_id =  models.IntegerField(default=0,verbose_name='Share ID')
    state_id = models.IntegerField(default=0,verbose_name='State ID')
    city_name = models.CharField(max_length=20,verbose_name='City Name')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

class tbl_company_mst(models.Model):
    company_id = models.IntegerField(default=0,verbose_name='Company ID',unique=True)
    share_id  = models.IntegerField(default=0,verbose_name='Share ID')
    entity_share_id = models.TextField(verbose_name='Entity Share ID')
    company_name = models.CharField(max_length=30)
    company_shortname = models.CharField(max_length=30)
    location_ref_id = models.ForeignKey("tbl_location_mst", default=0,verbose_name="Location Ref ID",on_delete=models.PROTECT)
    ownership_status_ref_id =  models.ForeignKey("tbl_master", default=0,verbose_name="Ownership Status Ref ID",on_delete=models.PROTECT)
    cin = models.CharField(max_length=21)
    pan = models.CharField(max_length=15)
    tan = models.CharField(max_length=15)
    gst = models.CharField(max_length=15)
    email = models.EmailField(blank=True)
    contact_person_name = models.CharField(max_length=30)
    currency_id = models.ForeignKey(Tbl_Currency_Mst, on_delete=models.CASCADE, blank=True, null=True)
    is_holding_company = models.BooleanField(blank=False)
    belongs_to_company_id = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='belongs_to')
    is_this_under_same_management = models.BooleanField()
    management_belongs_to_company_id = models.ForeignKey('self', on_delete=models.CASCADE,blank=True, null=True, related_name='managed_by')
    percentage_holding = models.FloatField()
    is_group_company = models.BooleanField()
    contact_person_mobile_number = models.IntegerField(null=True)
    is_this_branch = models.BooleanField()   
    pincode = models.CharField(max_length=8)
    ad_code = models.IntegerField(default=0, blank=True, null=True)
    iec_code = models.IntegerField(default=0, blank=True, null=True)
    import_ad_code = models.IntegerField(default=0, blank=True, null=True)
    import_iec_code = models.IntegerField(default=0, blank=True, null=True)
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

class Tbl_Daily_Currency_Rate_Mst(models.Model):
    share_id =  models.IntegerField(default=0,verbose_name='Share ID')
    current_date = models.DateField(verbose_name='Current Date')
    from_currrency_id = models.IntegerField(default=0,verbose_name='From Currency ID')
    to_currrency_id = models.IntegerField(default=0,verbose_name='To Currency ID')
    rate = models.FloatField(default=0.0000,verbose_name='Rate')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

class Tbl_Calendar_Mst(models.Model):
    share_id =  models.IntegerField(default=0,verbose_name='Share ID')
    calendar_type_id = models.IntegerField(default=0,verbose_name='Calendar Type ID')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

class Tbl_Calendar_Details(models.Model):
    mst_ref_id = models.IntegerField(default=0,verbose_name='Master Reference ID')
    year = models.CharField(max_length=4,verbose_name='Year')
    period = models.CharField(max_length=2,verbose_name='Period')
    start_date = models.DateField(verbose_name='Start Date')
    end_date = models.DateField(verbose_name='End Date')
    month = models.CharField(max_length=10,verbose_name='Month')
    status = models.TextField(verbose_name='Status')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

class tbl_master(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    master_type = models.CharField(max_length=20,verbose_name='Master Type')
    master_value = models.CharField(max_length=20,verbose_name='Master Value')
    master_key = models.CharField(max_length=20,verbose_name='Master Key')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

class Tbl_Transaction_Type_Mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    name = models.CharField(max_length=20,verbose_name='Name')
    tbl_transaction_header = models.CharField(max_length=40,verbose_name='Table Transaction Header')
    tbl_transaction_details = models.CharField(max_length=40,verbose_name='Table Transaction Details')
    join_condition = models.TextField(verbose_name='Join Condition')
    tbl_accounting = models.CharField(max_length=40,verbose_name='Table Accounting')
    tbl_sub_accounting_summary = models.CharField(max_length=40,verbose_name='Table Sub-Accounting Summary')
    ref_id_2_column = models.CharField(max_length=40,verbose_name='Reference ID-2 Column')
    is_accounting_required = models.CharField(default='N',max_length=1,verbose_name='Is Accounting Required')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

class Tbl_Transaction_Type_Details(models.Model):
    mst_ref_id = models.IntegerField(default=0,verbose_name='Master Reference ID')
    ref_name = models.CharField(max_length=10,verbose_name='Reference Name')
    value = models.CharField(max_length=40,verbose_name='Value')
    key = models.CharField(max_length=40,verbose_name='Key')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

class Tbl_Document_Sequencing_Mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    transaction_type_ref_id = models.IntegerField(default=0, verbose_name='Transaction Type Reference ID')
    year = models.CharField(max_length=4,verbose_name='Year')
    starting_no = models.CharField(max_length=20,verbose_name='Starting Number')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

class Tbl_Journal_Type_Mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    name = models.CharField(max_length=40,verbose_name='Name')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

class tbl_term_mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    term_code = models.CharField(max_length=10,verbose_name='Term Code')
    term_description = models.TextField(verbose_name='Term Description')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

    class Meta:
       constraints = [
           models.UniqueConstraint(fields = ['term_code'], condition=models.Q(is_deleted = 'N'), name='unique in term not deleted')
       ]

class tbl_location_mst(models.Model):
    location_name = models.CharField(max_length=255,verbose_name="Location Name")
    address1 = models.CharField(max_length=500,verbose_name="Address1")
    address2 = models.CharField(max_length=500,verbose_name="Address2")
    address3 = models.CharField(max_length=500,verbose_name="Address3")
    country_id = models.IntegerField(default=0,verbose_name="Country ID")
    state_id = models.IntegerField(default=0,verbose_name="State ID")
    city_id = models.IntegerField(default=0,verbose_name="City ID")
    is_deleted = models.CharField(max_length=1,default="N",verbose_name="Is Deleted Flag")
    is_active = models.CharField(max_length=1,default="Y",verbose_name="Is Active Flag")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    created_date_time = models.DateTimeField(verbose_name="Created Datetime",auto_now_add=True)
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    updated_date_time = models.DateTimeField(verbose_name="Updated Datetime",auto_now_add=True)
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub Application Id")
    application_id = models.CharField(max_length=20,verbose_name="Application Id")  

    class Meta:
        constraints = [
           models.UniqueConstraint(fields = ['location_name'], condition=models.Q(is_deleted = 'N'), name='unique if not deleted')
       ]

    def delete(self):
        self.is_deleted = 'Y'
        self.save()

class tbl_channel_mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    company_ref_id = models.ForeignKey("tbl_company_mst", default=0, verbose_name="Company Ref Id", on_delete=models.PROTECT)
    name = models.CharField(max_length=20,verbose_name='Name')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")  

class tbl_source_mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    company_ref_id = models.ForeignKey("tbl_company_mst", default=0, verbose_name="Company Ref Id", on_delete=models.PROTECT)
    name = models.CharField(max_length=20,verbose_name='Source Name')
    file_type_ref_id =  models.ForeignKey("tbl_master", default=0,verbose_name="File Type Ref ID",on_delete=models.PROTECT)
    from_date = models.DateField(verbose_name="From Date",auto_now_add=False)
    to_date = models.DateField(verbose_name="To Date",auto_now_add=False)
    revision_status = models.CharField(max_length=20,verbose_name="Revision Status")
    version_number = models.IntegerField(default=0,verbose_name='Version Number')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

class tbl_source_details(models.Model):
    header_ref_id = models.ForeignKey("tbl_source_mst", default=0,verbose_name="Header Ref ID",on_delete=models.PROTECT)
    section_identifier_id = models.CharField(max_length=20,verbose_name='Section Reference ID')
    field_name = models.CharField(max_length=20,verbose_name="Field Name")
    field_data_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Field Data Type ID",on_delete=models.PROTECT)
    field_length = models.IntegerField(verbose_name='Field Length')
    is_key_field = models.CharField(max_length=1, default='N',verbose_name='Is Key Field')
    is_primary_field = models.CharField(max_length=1, default='N',verbose_name='Is Primary Field')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

class tbl_reconcilation_definition_mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    company_ref_id = models.ForeignKey("tbl_company_mst", default=0, verbose_name="Company Ref Id", on_delete=models.PROTECT)
    name = models.CharField(max_length=20,verbose_name='Reconcilation Name')
    recon_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Recon Type Ref ID",on_delete=models.PROTECT)
    source_name1_ref_id = models.ForeignKey("tbl_source_mst", default=0,verbose_name="Source Name 1 Ref ID",on_delete=models.PROTECT,related_name='source_name1')
    source_name2_ref_id = models.ForeignKey("tbl_source_mst", default=0,verbose_name="Source Name 2 Ref ID",on_delete=models.PROTECT,related_name='source_name2')
    source_name3_ref_id = models.ForeignKey("tbl_source_mst", default=0,verbose_name="Source Name 3 Ref ID",on_delete=models.PROTECT,related_name='source_name3')
    source_name4_ref_id = models.ForeignKey("tbl_source_mst", default=0,verbose_name="Source Name 4 Ref ID",on_delete=models.PROTECT,related_name='source_name4')
    source_name5_ref_id = models.ForeignKey("tbl_source_mst", default=0,verbose_name="Source Name 5 Ref ID",on_delete=models.PROTECT,related_name='source_name5')
    recon_rule = models.TextField(verbose_name='Recon Rule')
    probable_match_rule = models.TextField(verbose_name='Probable Match Rule')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")      

class tbl_reconcilation_definition_details(models.Model):
    header_ref_id = models.ForeignKey("tbl_reconcilation_definition_mst", default=0,verbose_name="Header Ref ID",on_delete=models.PROTECT)
    details_id = models.IntegerField(default=0,verbose_name='Details Id')
    source_name_1_ref_id = models.ForeignKey("tbl_source_mst", default=0,verbose_name="Source Name 1 Ref ID",on_delete=models.PROTECT,related_name='details_source_name1')
    source_name_1_field_name = models.CharField(max_length=20, default=0,verbose_name='Source Name 1 Field Name')
    source_name_1_section_identifier_id = models.IntegerField(default=0,verbose_name='Source Name 1 Section Identifier ID')
    source_name_2_ref_id = models.ForeignKey("tbl_source_mst", default=0,verbose_name="Source Name 2 Ref ID",on_delete=models.PROTECT,related_name='details_source_name2')
    source_name_2_field_name = models.CharField(max_length=20, default=0,verbose_name='Source Name 2 Field Name')
    source_name_2_section_identifier_id = models.IntegerField(default=0,verbose_name='Source Name 2 Section Identifier ID')
    source_name_3_ref_id = models.ForeignKey("tbl_source_mst", default=0,verbose_name="Source Name 3 Ref ID",on_delete=models.PROTECT,related_name='details_source_name3')
    source_name_3_field_name = models.CharField(max_length=20, default=0,verbose_name='Source Name 3 Field Name')
    source_name_3_section_identifier_id = models.IntegerField(default=0,verbose_name='Source Name 3 Section Identifier ID')
    source_name_4_ref_id = models.ForeignKey("tbl_source_mst", default=0,verbose_name="Source Name 4 Ref ID",on_delete=models.PROTECT,related_name='details_source_name4')
    source_name_4_field_name = models.CharField(max_length=20, default=0,verbose_name='Source Name 4 Field Name')
    source_name_4_section_identifier_id = models.IntegerField(default=0,verbose_name='Source Name 4 Section Identifier ID')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")           

class tbl_api_definition_standard_mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    company_ref_id = models.ForeignKey("tbl_company_mst", default=0, verbose_name="Company Ref Id", on_delete=models.PROTECT)
    channel_ref_id = models.ForeignKey("tbl_channel_mst", default=0,verbose_name="Channel Ref Id",on_delete=models.PROTECT)
    from_date = models.DateField(verbose_name="From Date",auto_now_add=False)
    to_date = models.DateField(verbose_name="To Date",auto_now_add=False)
    revision_status = models.CharField(max_length=20,verbose_name="Revision Status")
    self_api= models.CharField(default='N',max_length=1,verbose_name='Self API')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")      

class tbl_api_definition_standard_details(models.Model):
    header_ref_id = models.ForeignKey("tbl_api_definition_standard_mst", default=0,verbose_name="Header Ref ID",on_delete=models.PROTECT)
    request_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Request Type Ref Id",on_delete=models.PROTECT ,related_name='request_to')
    api_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="API Type Ref Id",on_delete=models.PROTECT ,related_name='api_type')
    protocol_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Protocol Type Ref ID",on_delete=models.PROTECT ,related_name='protocol_ref')
    file_format_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="File Format Type Ref ID",on_delete=models.PROTECT ,related_name='file_format')
    authentication_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Authentication Type Ref Id",on_delete=models.PROTECT ,related_name='authentication_type')
    communication_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Communication Ref Id",on_delete=models.PROTECT ,related_name='communication_ref') 
    session_key_encryption_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Session Key Ref Id",on_delete=models.PROTECT ,related_name='session')
    encryption_type_ref_id = models.ForeignKey("tbl_master", default=0,verbose_name="Encryption Type Ref Id",on_delete=models.PROTECT ,related_name='encryption')
    port= models.IntegerField(default=0,verbose_name='Port')
    verification_algorithm_ref_id= models.ForeignKey("tbl_master", default=0,verbose_name="Verification Algo Type Ref Id",on_delete=models.PROTECT)
    end_point_url= models.CharField(max_length=20,verbose_name='End Point URL')
    time_out= models.IntegerField(default=0,verbose_name='Time Out')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")  

class tbl_api_definition_mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    name = models.IntegerField(default=0,verbose_name='Transaction ID')
    request_type_ref_id =models.IntegerField(default=0,verbose_name='Channel Ref Id')
    company_ref_id = models.ForeignKey("tbl_company_mst", default=0, verbose_name="Company Ref Id", on_delete=models.PROTECT)
    channel_ref_id = models.ForeignKey("tbl_channel_mst", default=0,verbose_name="Channel Ref Id",on_delete=models.PROTECT ,related_name='channel_ref_id')
    self_channel_ref_id = models.ForeignKey("tbl_channel_mst", default=0,verbose_name="Self Channel Ref Id",on_delete=models.PROTECT)
    source_name_ref_id = models.IntegerField(default=0,verbose_name='Source Name Ref ID')
    from_date = models.DateField(verbose_name="From Date",auto_now_add=False)
    to_date = models.DateField(verbose_name="To Date",auto_now_add=False)
    revision_status = models.CharField(max_length=20,verbose_name="Revision Status")
    time_out= models.IntegerField(default=0,verbose_name='Time out')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")   

class tbl_api_definition_details(models.Model):
    header_ref_id = models.ForeignKey("tbl_api_definition_mst", default=0,verbose_name="Header Ref ID",on_delete=models.PROTECT)
    api_field_name = models.CharField(max_length=20,verbose_name='API Field Name')
    api_field_data_type_ref_id = models.IntegerField(default=0,verbose_name='API Field Data Type Ref Id')
    api_field_length = models.IntegerField(default=0,verbose_name='API Field Length')
    table_name = models.CharField(max_length=20,verbose_name='Table Name')
    field_name =models.IntegerField(default=0,verbose_name='Field Name')
    field_data_type_ref_id = models.IntegerField(default=0,verbose_name='Field Data Type Ref Id')
    field_length = models.IntegerField(default=0,verbose_name='Field Length')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")    

class tbl_reconcilation_process_mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    name = models.CharField(max_length=20,verbose_name='Process Name')
    reconcilation_ref_id = models.IntegerField(default=0,verbose_name='Reconcilation Ref ID')
    api_ref_id = models.IntegerField(default=0,verbose_name='API Ref ID')
    request_type_ref_id =models.IntegerField(default=0,verbose_name='Request Type Ref Id')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")  

class tbl_reconcilation_process_details(models.Model):
    header_ref_id = models.IntegerField(default=0,verbose_name='Header Ref ID')
    operation_ref_id = models.IntegerField(default=0,verbose_name='Operation Ref ID')
    source_name_ref_id = models.IntegerField(default=0,verbose_name='Source Name Ref ID')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")        

class tbl_schedule_process_mst(models.Model):
    share_id = models.IntegerField(default=0,verbose_name='Share ID')
    process_ref_id = models.IntegerField(default=0,verbose_name='Process Ref ID')
    frequncy_ref_id = models.IntegerField(default=0,verbose_name='Frequency Ref ID')
    start_time = models.DateTimeField(default=timezone.localtime,verbose_name="Start Time")
    planned_execution_ref_id =models.IntegerField(default=0,verbose_name='Planned Execution Ref Id')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")      

class tbl_activity_mst(models.Model):
    process_ref_id = models.IntegerField(default=0,verbose_name='Process Ref ID')
    transaction_sequence_no = models.IntegerField(default=0,verbose_name='Transaction Sequence No')
    planned_start_time = models.DateTimeField(default=0,verbose_name='Process Ref ID')
    actual_start_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    actual_end_time = models.DateTimeField(default=timezone.localtime,verbose_name="Actual Date Time")
    status = models.CharField(max_length=20,verbose_name='Status')
    log_ref_id = models.IntegerField(default=0,verbose_name='Log Ref ID')
    remarks = models.TextField(verbose_name='Remarks')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")

class tbl_activity_details(models.Model):
    header_ref_id = models.ForeignKey("tbl_activity_mst", default=0,verbose_name="Header Ref ID",on_delete=models.PROTECT)
    operation_ref_id = models.IntegerField(default=0,verbose_name='Operation Ref ID')
    transaction_sub_sequence_no = models.IntegerField(default=0,verbose_name='Transaction Sub Sequence No')
    actual_start_time = models.DateTimeField(default=timezone.localtime,verbose_name="Actual Start Time")
    actual_end_time = models.DateTimeField(default=timezone.localtime,verbose_name="Actual End Time")
    status = models.CharField(max_length=20,verbose_name='Status')
    log_ref_id = models.IntegerField(default=0,verbose_name='Log Ref ID')
    remarks = models.TextField(verbose_name='Remarks')
    is_active = models.CharField(default='Y',max_length=1,verbose_name='Is Active')
    is_deleted = models.CharField(max_length=1, default='N',verbose_name="Is Deleted")
    created_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Created Date Time")
    created_by = models.IntegerField(default=0,verbose_name="Created By")
    updated_date_time = models.DateTimeField(default=timezone.localtime,verbose_name="Updated Date Time")
    updated_by = models.IntegerField(default=0,verbose_name="Updated By")
    sub_application_id = models.CharField(max_length=20,verbose_name="Sub-Application ID")
    application_id = models.CharField(max_length=20,verbose_name="Application ID")      


